---
apiVersion: v1
kind: Namespace
metadata:
  name: network-test
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    app: orchestrator
  template:
    metadata:
      name: orchestrator
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: luanguimaraesla/netperf:0.2.0
        imagePullPolicy: Always
        args:
        - --mode=orchestrator
        # - -debug
        ports:
        - name: service-port
          protocol: TCP
          containerPort: 5202
